CREATE TABLE IF NOT EXISTS channel_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_name VARCHAR(255) NOT NULL,
    channel_id VARCHAR(255) NOT NULL,
    uploads_playlist_id VARCHAR(255),
    CONSTRAINT uk_channel_configs_channel_id UNIQUE (channel_id)
);

INSERT INTO channel_configs (channel_name, channel_id, uploads_playlist_id) VALUES
    ('Marvel Entertainment',       'UCvC4D8onUfXzvjTOM-dBfEA', 'UUvC4D8onUfXzvjTOM-dBfEA'),
    ('Warner Bros. Pictures',      'UC_IRYSp4auq7hKLvziWVH6w', 'UU_IRYSp4auq7hKLvziWVH6w'),
    ('Universal Pictures',         'UCOwaTlA0nHlqMf4HBEWmLaw', 'UUOwaTlA0nHlqMf4HBEWmLaw'),
    ('Sony Pictures Entertainment','UCiifkYAs_bq1pt_zbNAzYGg', 'UUiifkYAs_bq1pt_zbNAzYGg'),
    ('Paramount Pictures',         'UCF0cXjaNm5Vx7EdCK4cxsYQ', 'UUF0cXjaNm5Vx7EdCK4cxsYQ'),
    ('20th Century Studios',       'UC-sSERhv7LzPWA3TxjzXJkw', 'UU-sSERhv7LzPWA3TxjzXJkw'),
    ('Disney',                     'UCYK0VLj-8kI2xJZRCCYgYnw', 'UUYK0VLj-8kI2xJZRCCYgYnw'),
    ('Paramount Movies UK',        'UCXwyXuLskuYsZiWNh0STJdw', 'UUXwyXuLskuYsZiWNh0STJdw'),
    ('Sky Cinema',                 'UCP6T93Fe7qKYlvb_5Cs8Z4g', 'UUP6T93Fe7qKYlvb_5Cs8Z4g'),
    ('Universal Movies International', 'UC2QJf3QCNwYt8GeNPP5fJhg', 'UU2QJf3QCNwYt8GeNPP5fJhg'),
    ('T-Series',                   'UCq-Fj5jknLsUf-MWSy4_brA', 'UUq-Fj5jknLsUf-MWSy4_brA'),
    ('YRF - Yash Raj Films',       'UCbTLwN10NoCU4WDzLf1JMOA', 'UUbTLwN10NoCU4WDzLf1JMOA'),
    ('Zee Studios',                'UC3jMepkLKF8y4iiwWmAB3RA', 'UU3jMepkLKF8y4iiwWmAB3RA'),
    ('Sony',                       'UC56gTxNs4f9xZ7Pa2i5xNzg', 'UU56gTxNs4f9xZ7Pa2i5xNzg');
